# Generated by Django 5.2.6 on 2025-09-12 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='likeditem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='likeditem',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='likeditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='likeditem',
            index=models.Index(fields=['content_type', 'object_id'], name='likes_liked_content_7292dd_idx'),
        ),
        migrations.AddIndex(
            model_name='likeditem',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='likes_liked_user_id_547501_idx'),
        ),
        migrations.AddConstraint(
            model_name='likeditem',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_content_like'),
        ),
    ]
