# Generated by Django 5.2.6 on 2025-09-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_discount_active_product_discount_label_and_more'),
    ]

    operations = [
    ]
