# Generated by Django 5.2.6 on 2025-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
