# Generated by Django 5.2.6 on 2025-09-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes_count',
        ),
    ]
