# Generated by Django 5.2.11 on 2026-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('perks_description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('coming_soon', models.BooleanField(default=False)),
                ('eta', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('link', models.CharField(blank=True, max_length=512)),
                ('link_type', models.CharField(blank=True, choices=[('product', 'Product'), ('category', 'Category'), ('external', 'External')], max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('animation', models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide', 'Slide'), ('scale', 'Scale'), ('bounce', 'Bounce')], default='none', max_length=20)),
                ('zone', models.CharField(choices=[('hero', 'Hero'), ('promotions-grid', 'Promotions Grid'), ('category-banner', 'Category Banner'), ('checkout-banner', 'Checkout Banner')], default='hero', max_length=32)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='chapa_tx_ref',
        ),
    ]
